version: 2
updates:
    # Maintain dependencies for GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      reviewers:
          - "greyscaled"
      rebase-strategy: disabled

    # Maintain dependencies for Yarn (npm)
    - package-ecosystem: "npm"
      directory: "/"
      groups:
          fe-deps:
              patterns:
                  - "*"
      schedule:
          interval: "weekly"
      reviewers:
          - "greyscaled"
      rebase-strategy: disabled
